# Generated by Django 5.1.7 on 2025-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='student',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
