# Generated by Django 5.1.7 on 2025-04-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_student_alter_issue_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='course',
        ),
    ]
