# Generated by Django 5.1.7 on 2025-04-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueCategory',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='issues.user'),
        ),
    ]
